[functions]
  external_node_modules = ["express", "pug"]
  node_bundler = "esbuild"
  included_files = ["views/**", "public/**", "locales/**"]
[[redirects]]
  from = "/images/*"
  to = "/public/images/:splat"
  status = 200
[[redirects]]
  force = true
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
[dev]
  publish = "public"